name: Hadolint
on:
  push:
  pull_request:
jobs:
  lint_teachers_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./Dockerfile
          config: ./.hadolint.yml